window.TZ_DB = {
   "001": {
    name: "Goukakyuu no Jutsu",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Katon",
    seals: "Sí",
    cost: "35 chakra",
    damage: "60 PV",
    range: "10 m (Chunin+: 15 m)",
    desc: "Una bola de fuego de 3 metros de diámetro es despedida desde la boca del ejecutor, avanzando en línea recta hasta una distancia de 10 metros. Si el usuario es chunin o superior, el alcance incrementa 5 metros más."
  },
  "002": {
    name: "Ryuuka no Jutsu",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Katon",
    seals: "Sí (mantener último)",
    cost: "35 chakra",
    damage: "60 PV",
    range: "Variable (según medio)",
    desc: "Requiere un medio físico para trasladarse (hilos metálicos o suelo). El ejecutor libera una fina llamarada que avanza hasta su objetivo y explota en un frenesí de llamas de 2 m de diámetro. Sobre el suelo: 10 m de alcance. Sobre hilos: alcance igual a la longitud del medio."
  },
  "003": {
    name: "Kasumi Enbu no Jutsu",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Katon",
    seals: "Sí",
    cost: "30 chakra",
    damage: "60 PV (explosión)",
    range: "10 m Ø / 2 turnos",
    desc: "De la boca del usuario se despide una nube de gas altamente inflamable de coloración grisácea. Abarca 10 metros de diámetro, centrada hasta 5 m del ejecutor. Puede permanecer 2 turnos y explota ante la más mínima chispa."
  },
  "004": {
    name: "Jihanensho no Jutsu",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Katon",
    seals: "Sí",
    cost: "30 chakra",
    damage: "—",
    range: "Radio 10 m",
    desc: "El usuario dispersa chakra de naturaleza fuego para hacer arder objetos propensos a ello (paja, alcohol, sellos explosivos, etc.) en un radio de 10 m. No afecta objetos imbuidos de chakra ajeno ni ropa de otros personajes."
  },
  "005": {
    name: "Akai Dangan",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Katon",
    seals: "Sí",
    cost: "50 chakra",
    damage: "90 PV",
    range: "15 m",
    desc: "Un cúmulo de llamas comprimidas en forma de bala de 20 cm de diámetro sale disparado de la boca del usuario hasta 15 m. Tras el impacto, las llamas se dispersan en un área de 1×1 metro."
  },
  "006": {
    name: "Hibashiri",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Katon",
    seals: "Sí",
    cost: "50 chakra",
    damage: "80 PV",
    range: "Anillo hasta 5 m Ø",
    desc: "Del suelo brotan llamas formando un anillo de hasta 5 m de diámetro y 2 m de altura que se comprime para atacar desde todas las direcciones. El centro del anillo no puede estar a más de 10 m del ejecutor."
  },
  "007": {
    name: "Bouka Kauten",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Katon",
    seals: "Sí",
    cost: "50 chakra",
    damage: "80 PV",
    range: "120° / 10 m",
    desc: "El usuario gira su cuello liberando una gran llamarada, formando una cortina de fuego de 2 m de altura que avanza 10 m cubriendo un arco de 120 grados."
  },
  "008": {
    name: "Karyuu Endan",
    rank: "Jounin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Katon",
    seals: "Sí",
    cost: "75 chakra",
    damage: "135 PV",
    range: "20 m (5×5 m)",
    desc: "Llamarada de altísima temperatura que adopta la forma de un dragón oriental de fuego de 5 m de ancho y 5 m de alto, avanzando linealmente hasta 20 metros desde la boca del ejecutor."
  },
  "009": {
    name: "Zukokku",
    rank: "Jounin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Katon",
    seals: "Sí",
    cost: "75 chakra",
    damage: "120 PV",
    range: "20 m (muro 20×10 m)",
    desc: "Gran llamarada que forma un muro de fuego de 20 m de longitud y 10 m de altura, avanzando linealmente hasta 20 metros con gran poder destructivo."
  },
  "010": {
    name: "Dai Endan",
    rank: "Jounin Élite",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Katon",
    seals: "Sí",
    cost: "100 chakra",
    damage: "180 PV",
    range: "35 m (5×5 m)",
    desc: "Llamarada de temperatura extrema con poder destructivo devastador. Las llamas se propagan 5 m de ancho y 5 m de alto, con un alcance total de 35 metros."
  },
 
  /* ---- SUITON ---- */
  "011": {
    name: "Mizu Shooku",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Suiton",
    seals: "Sí",
    cost: "35 chakra",
    damage: "60 PV",
    range: "10 m (Chunin+: 15 m)",
    desc: "Un chorro de agua a presión de 2 m de diámetro liberado desde la boca del usuario. Alcance de 10 metros. A rango chunin, el alcance aumenta 5 metros más."
  },
  "012": {
    name: "Hogo Suikyuu",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental / Barrera",
    element: "Suiton",
    seals: "Sí (mantener último)",
    cost: "35 chakra",
    damage: "Resistencia: 60 pts",
    range: "Barrera personal",
    desc: "La humedad del ambiente se condensa formando una esfera de agua alrededor del usuario con 60 puntos de resistencia. Requiere mantener el último sello hasta que desaparezca o cumpla su función."
  },
  "013": {
    name: "Suichuu Joushou",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Suiton",
    seals: "Sí",
    cost: "35 chakra",
    damage: "60 PV",
    range: "Req. fuente agua / 10 m",
    desc: "Requiere que ejecutor y adversario estén sobre una fuente de agua a al menos 10 m de distancia. Desde los pies del rival emerge un chorro ascendente. Un ligero burbujeo precede la técnica."
  },
  "014": {
    name: "Shitsudo no Jutsu",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Suiton",
    seals: "Sí",
    cost: "30 chakra",
    damage: "—",
    range: "Radio 10 m",
    desc: "El usuario impregna el ambiente de humedad en un radio de 10 m. Deshabilita sellos explosivos, inutiliza objetos propensos al fuego y extingue pequeñas llamas en el área."
  },
  "015": {
    name: "Mizurappa",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Suiton",
    seals: "Sí",
    cost: "50 chakra",
    damage: "90 PV",
    range: "15 m",
    desc: "Un potente chorro de agua de 2 m de diámetro despedido desde la boca del usuario, alcanzando hasta 15 metros de distancia."
  },
  "016": {
    name: "Arechi no Ike",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Suiton",
    seals: "Sí",
    cost: "50 chakra",
    damage: "—",
    range: "15 m radio / 3 turnos",
    desc: "Crea una fuente de agua de 15 m de radio y 50 cm de profundidad centrada en el usuario. Dura tres turnos. A rango jounin la profundidad aumenta a 1 metro."
  },
  "017": {
    name: "Oukina Nami",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Suiton",
    seals: "Sí",
    cost: "50 chakra",
    damage: "80 PV",
    range: "15 m (ola 10×4 m)",
    desc: "Requiere fuente de agua de al menos 1 m de profundidad. Crea una gran ola de 10 m de longitud y 4 m de altura que avanza linealmente hasta 15 metros, arrasando todo a su paso."
  },
  "018": {
    name: "Suiryuudan no Jutsu",
    rank: "Jounin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Suiton",
    seals: "Sí (mantener último)",
    cost: "75 chakra",
    damage: "135 PV",
    range: "Radio 20 m / dragón 2 m Ø",
    desc: "Crea un dragón de agua de 2 m de diámetro manejable libremente en un radio de 20 m. Puede condensar la humedad ambiental o usar una fuente acuática. Mantener el último sello mientras esté activo."
  },
  "019": {
    name: "Suigadan",
    rank: "Jounin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Suiton",
    seals: "Uno",
    cost: "75 chakra",
    damage: "120 PV",
    range: "5 m del ejecutor",
    desc: "Requiere fuente de agua de al menos 1 m de profundidad. Un colmillo de agua de 30 cm de diámetro emerge abruptamente hasta 2 m de alto. Produce una ligera vibración antes de activarse."
  },
  "020": {
    name: "Bakusui Shouha",
    rank: "Jounin Élite",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Suiton",
    seals: "Sí (1 turno completo)",
    cost: "100 chakra",
    damage: "—",
    range: "35 m radio / 15 m prof.",
    desc: "El usuario libera una cantidad colosal de agua que inunda el terreno en un radio de 35 m con 15 m de profundidad. Requiere un turno completo para concretarse."
  },
"021": {
    name: "Raikyuu",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Raiton",
    seals: "Sí",
    cost: "35 chakra",
    damage: "60 PV",
    range: "10 metros",
    desc: "Una esfera eléctrica de medio metro de diámetro se forma entre las palmas del usuario. Dicha esfera podrá ser arrojada hasta una distancia de 10 metros y al impactar liberará una corriente eléctrica que afecta una zona de 1x1 metros. A rango chunin aumente el alcance de lo que puede arrojarse en 5 metros más."
  },
  "022": {
    name: "Bunya Denki no jutsu",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Raiton",
    seals: "Sí",
    cost: "35 chakra",
    damage: "60 PV",
    range: "15 metros",
    desc: "Se utiliza una superficie sólida como un medio para propagar la electricidad. El usuario coloca ambas manos sobre el suelo y una corriente eléctrica saldrá despedida hacia la dirección que él desee, si durante ese trayecto se encuentra contra el adversario, la corriente ascenderá por su cuerpo y le ocasionará daños considerables. La distancia máxima a la que puede llegar es de 15 metros."
  },
  "023": {
    name: "Dendou panchi",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Raiton",
    seals: "Sí",
    cost: "35 chakra",
    damage: "60 PV",
    range: "10 metros",
    desc: "El usuario rodea su puño de una electricidad amarilla que es fácilmente perceptible. Tras lanzar un puñetazo al aire, la electricidad saldrá despedida rápidamente y de manera lineal, teniendo un alcance de 10 metros como máximo. Mientras el puño del usuario esté rodeado por la técnica, no podrá realizar sellos manuales, aunque sí podrá realizar jutsus que no requieran estos. La duración máxima de este efecto es de 2 turnos."
  },
  "024": {
    name: "Hogokyuu",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Raiton",
    seals: "Sí",
    cost: "30 chakra",
    damage: "No cuenta con daño asociado",
    range: "3 metros (radio)",
    desc: "El usuario conjura rayos a su alrededor de modo que lo rodeen formando una esfera completa de 3 metros de radio, misma que repele el ataque de armas arrojadizas sin chakra añadido y que también puede desactivar sellos explosivos dentro de ese rango."
  },

"025": {
    name: "Oukina Raikyuu",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Raiton",
    seals: "Sí",
    cost: "50 chakra",
    damage: "90 PV",
    range: "15 metros",
    desc: "Consiste en una esfera gigante, de 4 metros de diámetro, compuesta de rayos. Se origina desde la posición del usuario y avanza de manera lineal para barrer todo a su paso hasta una distancia de 15 metros."
  },
  "026": {
    name: "Denki sutonpu",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Raiton",
    seals: "Sí",
    cost: "50 chakra",
    damage: "80 PV",
    range: "10 metros (radio)",
    desc: "El usuario concentra chakra raiton sobre alguna de sus piernas y posteriormente da un fuerte pisotón sobre la superficie. La electricidad se dispersará hacia todas direcciones en un radio de 10 metros, afectando a todo aquel que se encuentre pisando la zona afectada."
  },
  "027": {
    name: "Raundo raikan",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Raiton",
    seals: "Sí",
    cost: "50 chakra",
    damage: "80 PV",
    range: "15 metros (radio)",
    desc: "Requiere que el usuario guarde tanto su posición como el último sello manual. Dentro de un radio de 15 metros, el ejecutor podrá concentrar la electricidad para formar un orbe de medio metro de diámetro que, tan pronto como se forma, estalla liberando rayos que afectan una zona de dos metros de diámetro. Antes de formarse el orbe, se aprecian pequeñas chispas en el ambiente."
  },
  "028": {
    name: "Rairyuu no Tatsumaki",
    rank: "Jounin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Raiton",
    seals: "Sí",
    cost: "75 chakra",
    damage: "135 PV",
    range: "20 metros (radio)",
    desc: "Un dragón hecho de rayos es creado desde la posición del ejecutor. Puede moverse libremente en un radio de 20 metros para atacar al objetivo. El dragón tiene un diámetro de 2 metros y su longitud puede crecer tanto como se desplace dentro del área designada."
  },
  "029": {
    name: "Raikoudaina",
    rank: "Jounin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Raiton",
    seals: "Sí",
    cost: "75 chakra",
    damage: "120 PV",
    range: "15 metros",
    desc: "Múltiples rayos se congregan alrededor del usuario para formen una esfera eléctrica que le rodea para, posteriormente, detonar y liberar la electricidad hacia todas direcciones. Afectando un área de 15 metros a la redonda y dañando a todo aquel que se encuentre en la zona."
  },
  "030": {
    name: "Kyodaina Rairyuu",
    rank: "Jounin élite",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Raiton",
    seals: "Sí",
    cost: "100 chakra",
    damage: "180 PV",
    range: "35 metros",
    desc: "Una inmensa cantidad de rayos se aglomeran junto al usuario para crear un enorme dragón eléctrico que avanza hasta 35 metros para barrer todo lo que se encuentre a su paso. Tiene una longitud de 5 metros de ancho y 5 de alto."
  },

"031": {
    name: "Juuha shou",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Fuuton",
    seals: "No",
    cost: "35 chakra",
    damage: "50 PV",
    range: "10 metros",
    desc: "Realizando un movimiento horizontal con el brazo, como si de un tajo al aire se tratase, se libera una onda de viento en forma de media luna. Mide 1 metro de longitud y avanza hasta 10 metros para impactar al objetivo."
  },
  "032": {
    name: "Reppuken",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Fuuton",
    seals: "Sí",
    cost: "35 chakra",
    damage: "60 PV",
    range: "10 metros",
    desc: "De la boca del usuario sale despedida una fuerte corriente de aire. Su ancho y su alto es de 2 metros y tiene un alcance de 10 metros, mismo que aumenta 5 metros más si se alcanza el rango chunin."
  },
  "033": {
    name: "Reppuushou",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Fuuton",
    seals: "No",
    cost: "10 chakra por arma arrojada",
    damage: "+10 puntos al daño del arma",
    range: "Depende del arma",
    desc: "Tras arrojar algún arma arrojadiza, surge una corriente de aire que aumenta tanto su velocidad de ataque (+10 de Aptitud) como el daño asociado a dicha arma (+10 puntos)."
  },
  "034": {
    name: "Eahando",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Fuuton",
    seals: "No",
    cost: "15 chakra por objeto",
    damage: "No cuenta con daño asociado",
    range: "10 metros (radio) / 3 metros",
    desc: "Se controlan las corrientes de aire de los alrededores del usuario, de modo que es capaz de controlar objetos ligeros (menos de 2 kg) para desplazarlos de posición, siempre y cuando se encuentren en un radio de 10 metros. En el nivel más básico puede mover solo un objeto a la vez, a rango chunin el número aumenta a dos y en jounin a cuatro. No puede mover objetos que estén impregnados con chakra ajeno. También puede usarse para recuperar objetos con rapidez y que estos vayan directamente a la palma de su mano, pero este efecto solo funciona en un radio de 3 metros."
  },
  "035": {
    name: "Kami Oroshi",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Fuuton",
    seals: "Sí",
    cost: "50 chakra",
    damage: "90 PV",
    range: "15 metros",
    desc: "Tras apuntar con ambas palmas, se crea un vórtex de viento de 2 metros de diámetro, mismo que avanza con ferocidad hasta 15 metros para atacar al objetivo designado."
  },
  "036": {
    name: "Bikkuri kuuken",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Fuuton",
    seals: "No",
    cost: "50 chakra",
    damage: "75 PV",
    range: "7 metros",
    desc: "Tras lanzar un puñetazo al aire, se desprende una ráfaga de vientos de un metro de diámetro. Su alcance no es muy largo, puesto que se limita a los 7 metros, pero su viabilidad radica en su facilidad de ejecución."
  },
  "037": {
    name: "Kaze hyoushi",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Fuuton",
    seals: "Uno",
    cost: "50 chakra",
    damage: "80 PV",
    range: "10 metros (radio)",
    desc: "El único sello requerido es juntar las palmas de las manos a la altura del pecho. Una corriente de viento descendiente se congrega para rodear el cuerpo del usuario y posteriormente propagarse hacia todas direcciones de manera violenta, abarcando un radio de 10 metros. En rango jounin es capaz de controlar las corrientes para que no afecten alguna zona en específico."
  },
  "038": {
    name: "Daitoppa",
    rank: "Jounin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Fuuton",
    seals: "Sí",
    cost: "75 chakra",
    damage: "135 PV",
    range: "20 metros",
    desc: "Tras apuntar con la palma de la mano hacia la ubicación deseada, se libera una potente ráfaga de vientos a gran velocidad. El ataque cuenta con un diámetro de 4 metros y recorre una distancia de 20 metros."
  },
  "039": {
    name: "Kaze jouzai",
    rank: "Jounin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Fuuton",
    seals: "Sí",
    cost: "75 chakra",
    damage: "120 PV",
    range: "15 metros",
    desc: "Se designa un point en el terreno que no esté a más de 15 metros de distancia con respecto al ejecutor. Posteriormente, tomando ese punto como referencia, un gran tornado de vientos se forma alrededor de manera violenta para aprisionar al o los objetivos. Tan pronto como se concreta su formación, las ráfagas de viento se comprimen para dañar todo aquello que se encuentre en su interior. El diámetro del tornado es de 10 metros y su altura de 15 metros."
  },
  "040": {
    name: "Atsugai",
    rank: "Jounin élite",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Fuuton",
    seals: "No",
    cost: "100 chakra",
    damage: "150 PV",
    range: "30 metros (radio)",
    desc: "Tras extender ambos brazos en direcciones opuestas, el usuario libera violentas ráfagas de aire que se propagan hacia todos lados, arrasando una zona de 30 metros a la redonda. Es la técnica devastadora por excelencia, pues combina la facilidad y velocidad de uso, junto a un efecto de área de gran daño. No obstante, el usuario no podrá desplazarse sino hasta que la técnica haya culminado."
  },
"041": {
    name: "Gaia no Kenshin",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Doton",
    seals: "Sí",
    cost: "35 chakra",
    damage: "60 PV",
    range: "10 metros",
    desc: "Se forma una grieta desde los pies del usuario, misma que avanza hasta la ubicación del objetivo y, al llegar a este, un pico compuesto de rocas emergerá para contactarle directamente. El pico tiene un largo de metro y medio, el alcance de este jutsu es de 10 metros y aumenta 5 metros más si se alcanza el rango chunin."
  },
  "042": {
    name: "Moguragakure no Jutsu",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Doton",
    seals: "Sí",
    cost: "25 chakra",
    damage: "No cuenta con daño asociado",
    range: "2 metros (profundidad)",
    desc: "El usuario, al transmitir su chakra al suelo, puede hacer que se convierta en arena fina, permitiéndole de esa forma incrustarse bajo tierra, hasta una profundidad de 2 metros, y moverse a través de ella. Estando sumergido, puede desplazarse a una tercera parte de su velocidad total. Puede durar bajo superficie 3 turnos, 4 en caso de ser chunin y 5 si es jounin."
  },
  "043": {
    name: "Shinjuuzanshu no Jutsu",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Doton",
    seals: "Sí",
    cost: "25 chakra",
    damage: "No cuenta con daño asociado",
    range: "Cuerpo a cuerpo",
    desc: "Requiere el Moguragakure no Jutsu activado. Tras situarse debajo de la posición del adversario, el usuario saca sus brazos a superficie y, con un rápido movimiento, jala los pies de la víctima para hundirlo bajo tierra hasta la altura de los hombros, a la vez que él emerge a superficie. Si la resistencia del contrincante es de 45 puntos o más, este efecto no puede realizarse. Cada turno sumergido en tierra (posterior al turno de inicio), la víctima gana 10 puntos de resistencia extra para buscar su liberación."
  },
  "044": {
    name: "Hyouki no Jutsu",
    rank: "Genin",
    type: "Ninjutsu",
    branch: "Elemental / sensorial",
    element: "Doton",
    seals: "No",
    cost: "25 chakra",
    damage: "No cuenta con daño asociado",
    range: "15 metros (radio)",
    desc: "Tras colocar alguna de sus palmas contra la superficie, el usuario transmits su chakra a través de esta para capturar las vibraciones presentes, de modo que se vuelve capaz de percibir los movimientos bajo tierra (a una profundidad de hasta 3 metros). También puede usarse de modo inverso, estando sumergido bajo tierra, para percibir los movimientos que ocurren por encima de la superficie. El radio de acción de esta percepción es de 15 metros."
  },
  "045": {
    name: "Gaia no Hitokajiri",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Doton",
    seals: "Sí",
    cost: "10 chakra por roca",
    damage: "18 PV por roca",
    range: "15 metros",
    desc: "Versión mejorada del Gaia no Kenshin. Ahora son 5 los picos rocosos que se liberan, mismos que pueden ir a un solo enemigo o atacar múltiples objetivos. El rango de acción aumenta hasta los 15 metros."
  },
  "046": {
    name: "Dochuu Senkou",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Doton",
    seals: "Sí",
    cost: "50 chakra",
    damage: "El que realice el arma",
    range: "15 metros / 20 metros",
    desc: "Las armas u objetos del usuario, mismas que deben estar sobre el suelo o haciendo contacto con este, serán tragadas por la tierra. El ejecutor podrá desplazarlas por debajo de la superficie y liberarlas en un nuevo punto, generalmente sobre la posición del adversario, donde podrán salir disparadas a gran velocidad para atacarle o liberarlas de manera parcial. Es necesario mantener el último sello de la técnica en todo momento. La velocidad de movimiento de las armas se rige con el atributo de control. Puede manejar hasta 3 armas o 5 si se cuenta con el rango jounin. El rango de manejo es de 15 metros o hasta 20 si se obtiene el rango jounin. Puede mantener esta técnica hasta por 2 turnos."
  },
  "047": {
    name: "Dorou Doumu",
    rank: "Chunin",
    type: "Ninjutsu",
    branch: "Elemental / Barrera",
    element: "Doton",
    seals: "Sí",
    cost: "50 chakra",
    damage: "No cuenta con daño asociado",
    range: "15 metros",
    desc: "Se colocan las palmas sobre la superficie para adquirir un control sobre el terreno de los alrededores y formar una cúpula de rocas compactas que rodea al adversario y lo atrapa en su interior. La cúpula tiene un diámetro de 5 metros y una altura similar, además de una resistencia de 90 puntos. El adversario puede anticiparse a su captura y escapar con un movimiento físico solo si su estadística de evasión es mayor que la estadística de control del ejecutor. La técnica puede realizarse hasta a una distancia de 15 metros."
  },
  "048": {
    name: "Doryuusou",
    rank: "Jounin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Doton",
    seals: "Sí",
    cost: "75 chakra",
    damage: "120 PV",
    range: "10 metros (radio)",
    desc: "El terreno comienza a condensarse de modo que la tierra, el barro o incluso el lodo, se solidifican en forma de lanzas y pinchos que sobresalen de manera abrupta afectando un área de 10 metros a la redonda. Estos picos tienen un gran poder ofensivo y alcanzan una altura de dos metros. En caso de que dos o más picos impacten a un mismo objetivo, el daño a los puntos de vida no se acumula. El centro de la zona afectada no puede estar a más de 15 metros de distancia del ejecutor. Antes de emerger, se puede percibir una ligera vibración."
  },
  "049": {
    name: "Rokkubureiku",
    rank: "Jounin",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Doton",
    seals: "Uno",
    cost: "75 chakra",
    damage: "135 PV",
    range: "Al menos 15 metros",
    desc: "Requiere que el adversario se encuentre dentro del Dorou Doumu o de algún jutsu afín. Tras realizar un único sello de manos, la prisión de rocas detonará violentamente, dispersando los fragmentos resultantes hacia el interior a modo de avalancha masiva y dañando a todos los que se encuentren dentro. Es necesario que el ejecutor mantenga una distancia de al menos 15 metros con la prisión rocosa."
  },
  "050": {
    name: "Doryuudan",
    rank: "Jounin élite",
    type: "Ninjutsu",
    branch: "Elemental",
    element: "Doton",
    seals: "Sí",
    cost: "100 chakra",
    damage: "150 PV",
    range: "25 metros",
    desc: "Delante del usuario (o a un costado suyo) surge una cabeza de dragón, de aproximadamente 3 metros de diámetro. Tras surgir, también se crea un río de lodo, de 4 metros de longitud, que avanza de manera lineal hasta recorrer una distancia de 25 metros, atrapando a todo aquel que se encuentre a su paso e imposibilitando su escape. De manera simultánea, la cabeza de dragón libera potentes disparos de lodo y fango comprimidos, de medio metro de diámetro, mismos que también tienen un alcance de 25 metros. La velocidad de propagation del río ocurre a +10 de control, mientras que los disparos ocurren a velocidad normal. Esta combinación asegura que el adversario primero quedará imposibilitado de escapar antes de encarar la ofensiva. No importa si el objetivo recibe uno o múltiples impactos, el daño no será el mismo."
  },

  "051": {
    name: "Henge no jutsu",
    rank: "Estudiante",
    type: "Ninjutsu",
    branch: "—",
    element: "No requiere",
    seals: "Sí",
    cost: "10 de chakra",
    damage: "No tiene daño asociado",
    range: "—",
    desc: "El usuario realiza una transformación visual, adoptando la apariencia de cualquier otra persona u objeto de un tamaño y masa similares. Esta transformación es meramente estética y no supone ningún cambio en las habilidades físicas, psicológicas, conocimientos, voz, color de chakra o cualquier otra cualidad. La transformación perdura hasta que el usuario así lo desee o hasta que recibe un impacto que haga más de 10 puntos de daño a su vida. Mantener esta técnica no entra en conflicto con otras técnicas."
  },
};
